// Generates config.local.js from environment variables. Run before loading
// the unpacked extension:
//
//   GEMINI_API_KEY=... node scripts/build-config.mjs
//
// The generated file is gitignored. background.js imports it as an ES module,
// so the key is never embedded in version-controlled source. For production,
// proxy Gemini through a backend instead of shipping the key client-side.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const out = join(root, "config.local.js");

const key = process.env.GEMINI_API_KEY || "";
if (!key) {
  console.warn(
    "[build-config] GEMINI_API_KEY not set — Gemini features will be disabled at runtime."
  );
}

const banner = "// Generated by scripts/build-config.mjs. Do not commit.\n";
const body = `export const GEMINI_API_KEY = ${JSON.stringify(key)};\n`;
writeFileSync(out, banner + body);
console.log(`[build-config] wrote ${out} (${key ? "key present" : "empty key"})`);
